server:
    port: 3000

spring:
    datasource:
        url: jdbc:sqlite:sqlite.db
        username: sanko
        password: sanko
        driver-class-name: org.sqlite.JDBC

mybatis:
    mapper-locations: classpath:mapper/*.xml