server:
    port: 3000

spring:
    datasource:
        url: jdbc:sqlite:sqlite.db
        username: sanko
        password: sanko
        driver-class-name: org.sqlite.JDBC
    session:
        store-type: jdbc
        jdbc:
            initialize-schema: always

mybatis:
    mapper-locations: classpath:mapper/*.xml