server:
    port: 3000

spring:
    datasource:
        url: jdbc:sqlite:sqlite.db
        username: sanko
        password: sanko
        driver-class-name: org.sqlite.JDBC
    sql:
        init:
            mode: always
    session:
        store-type: jdbc
        jdbc:
            initialize-schema: always
session:
    datasource:
        url: jdbc:sqlite:session.db
        username: sanko
        password: sanko

mybatis:
    mapper-locations: classpath:mapper/*.xml